homepage:
  path: /
  defaults: { _controller: AppBundle:Building:default }

enter:
  path: /enter
  defaults: { _controller: AppBundle:BuildingEnter:default }

exit:
  path: /exit
  defaults: { _controller: AppBundle:BuildingExit:default }

history:
  path: /history
  defaults: { _controller: AppBundle:Building:history, _format: json }